In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import numpy as np
from sklearn.preprocessing import MinMaxScaler

data  = pd.read_csv('Bicycle_Thefts_Open_Data.csv')

In [3]:
#Null Values
data_null_count = data.isnull().sum()
data_null_percentage = (data.isnull().sum() / data.shape[0]) * 100
null_values = pd.DataFrame({
    'Null Count': data_null_count,
    'Null Percentage': data_null_percentage
})

In [4]:
#handle uneligable value
data.replace(['-', '--', '----', '?', '??', '+'], pd.NA, inplace=True)

In [12]:
#Bike Make & Bike Color fill na with mode (categorical column)
data['BIKE_MAKE'].fillna(data['BIKE_MAKE'].mode()[0], inplace=True)
data['BIKE_COLOUR'].fillna(data['BIKE_COLOUR'].mode()[0], inplace=True)

data_null_count = data.isnull().sum()
data_null_percentage = (data.isnull().sum() / data.shape[0]) * 100
null_values = pd.DataFrame({
    'Null Count': data_null_count,
    'Null Percentage': data_null_percentage
})

In [5]:
#Bike Model -> 37% missing. Too many missing values so drop the colum
data.dropna(subset=['BIKE_MODEL'], inplace=True)

data_null_count = data.isnull().sum()
data_null_percentage = (data.isnull().sum() / data.shape[0]) * 100
null_values = pd.DataFrame({
    'Null Count': data_null_count,
    'Null Percentage': data_null_percentage
})



In [6]:
#Bike Speed & Bike Cost fill na with mean (numerical column)
data['BIKE_SPEED'].fillna(data['BIKE_SPEED'].mean(), inplace=True)
data['BIKE_COST'].fillna(data['BIKE_COST'].mean(), inplace=True)


data_null_count = data.isnull().sum()
data_null_percentage = (data.isnull().sum() / data.shape[0]) * 100
null_values = pd.DataFrame({
    'Null Count': data_null_count,
    'Null Percentage': data_null_percentage
})
#null_values

In [7]:
#encode column Bike_model. Lots of different categories so retain top 20 and the rest 'other'
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
#encode column Bike_model. Lots of different categories so retain top 20 and the rest 'other'
top_categories = 20
top_n_categories = data['BIKE_MODEL'].value_counts().nlargest(top_categories).index
data['BIKE_MODEL_CAT'] = data['BIKE_MODEL'].apply(lambda x: x if x in top_n_categories else 'Other')

data['BIKE_MODEL_IND'] = label_encoder.fit_transform(data['BIKE_MODEL_CAT'])
data['BIKE_MODEL_IND'].unique()

array([13,  8, 11,  0, 19,  4,  9,  3,  1, 20, 16,  5,  7, 10,  2, 17, 15,
        6, 14, 12, 18])

In [8]:
#encode column bike make. Lots of different categories so retain top 50 and the rest 'other'

top_categories = 50
top_n_categories = data['BIKE_MAKE'].value_counts().nlargest(top_categories).index
data['BIKE_MAKE_CAT'] = data['BIKE_MAKE'].apply(lambda x: x if x in top_n_categories else 'Other')

data['BIKE_MAKE_IND'] = label_encoder.fit_transform(data['BIKE_MAKE_CAT'])
data['BIKE_MAKE_IND'].unique()

array([12, 46, 16,  2, 30, 22, 31, 32, 34, 17, 49, 11, 47,  5,  9, 18, 42,
        6, 29, 33, 38, 41, 36, 35, 26, 21, 23, 45, 24, 40, 43, 13, 37, 14,
       25, 48,  3, 19, 44, 20,  0,  4, 10,  8, 39, 15,  7, 27,  1, 50, 28])

In [9]:
#encode column bike color. Lots of different categories so retain top 50 and the rest 'other'
top_categories = 50
top_n_categories = data['BIKE_COLOUR'].value_counts().nlargest(top_categories).index
data['BIKE_COLOUR_CAT'] = data['BIKE_COLOUR'].apply(lambda x: x if x in top_n_categories else 'Other')
data['BIKE_COLOUR_IND'] = label_encoder.fit_transform(data['BIKE_COLOUR_CAT'])
data['BIKE_COLOUR_IND'].unique()

array([35,  1, 11, 46, 36, 25, 23, 38, 50,  4, 43,  0,  7, 30, 42, 41,  2,
       32, 33, 10, 14, 13, 21,  9, 20, 22, 49, 18, 27, 34, 16, 29, 28,  8,
       40, 47, 45, 39,  5, 31,  3, 37, 44, 17, 19,  6, 12, 48, 26, 15, 24])

In [10]:
#encode column neighbourhood 158. Lots of different categories so retain top 50 and the rest 'other'
top_categories = 50
top_n_categories = data['NEIGHBOURHOOD_158'].value_counts().nlargest(top_categories).index
data['NEIGHBOURHOOD_158_CAT'] = data['NEIGHBOURHOOD_158'].apply(lambda x: x if x in top_n_categories else 'Other')
data['NEIGHBOURHOOD_158_IND'] = label_encoder.fit_transform(data['NEIGHBOURHOOD_158_CAT'])


In [11]:
#Bike Type
label_encoder = LabelEncoder()
data['BIKE_TYPE_IND'] = label_encoder.fit_transform(data['BIKE_TYPE'])
data['DIVISION_IND'] = label_encoder.fit_transform(data['DIVISION'])
data['LOCATION_TYPE_IND'] = label_encoder.fit_transform(data['LOCATION_TYPE'])
data['OCC_DOW_IND'] = label_encoder.fit_transform(data['OCC_DOW'])
data['OCC_MONTH_IND'] = label_encoder.fit_transform(data['OCC_MONTH'])
data['OCC_YEAR_IND'] = label_encoder.fit_transform(data['OCC_YEAR'])
data['PREMISES_TYPE_IND'] = label_encoder.fit_transform(data['PREMISES_TYPE'])
data['PRIMARY_OFFENCE_IND'] = label_encoder.fit_transform(data['PRIMARY_OFFENCE'])
data['REPORT_DOW_IND'] = label_encoder.fit_transform(data['REPORT_DAY'])
data['REPORT_MONTH_IND'] = label_encoder.fit_transform(data['REPORT_MONTH'])
data['REPORT_YEAR_IND'] = label_encoder.fit_transform(data['REPORT_YEAR'])
data['STATUS_IND'] = label_encoder.fit_transform(data['STATUS'])
data['REPORT_HOUR_IND'] = label_encoder.fit_transform(data['REPORT_HOUR'])
data['BIKE_MAKE_IND'] = label_encoder.fit_transform(data['BIKE_MAKE'])
data['BIKE_COLOUR_IND'] = label_encoder.fit_transform(data['BIKE_COLOUR'])
data['BIKE_COLOUR_IND'].unique()

array([194,   7,  33, 203, 156, 112,  97, 105, 176, 225, 188,  45, 219,
        18, 187,   0,  27, 130, 186, 183,  10, 140, 144,  32,  50,  46,
       196,  83,  31,  40,  75,  90,  42, 213,  67, 125, 153,  52, 159,
       100,  69, 169, 179, 128, 126,  28, 145, 182, 204, 199, 177,  30,
        23, 223, 214, 134, 122,  17, 167, 207, 197,  61, 227, 208,  21,
       129,  72, 185,  25,  16, 142, 190,  34, 212, 210, 164, 211,  63,
       171, 218, 206,  70,  35, 103, 137, 170, 166,  15,  19,  81, 205,
       113,  48, 195,  26,  12, 110,  20, 184,  51, 111,  94, 151,  38,
         6, 124,  84,  59,  98,  36,  39, 108, 221,  74,  99,   1,   9,
       118, 192,   5,  95,   3, 114,  44, 202,  71, 155, 160,  76,  68,
        43, 101, 178,  82, 173, 102, 158, 119, 181, 189, 120, 121, 220,
        92, 133, 165, 123,  65,  24, 193, 226, 217, 200, 143,  88, 149,
        29,  64,   8, 138, 222,  55, 180,  89, 109, 216,  80,  49, 215,
       132,  58, 117,  87,  54, 191, 175,  14, 107, 106,  85, 15

In [12]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder


# get numerical and categorical columns seperatly
numeric_columns = data.select_dtypes(include=['float64', 'int64']).columns
categorical_columns = data.select_dtypes(include=['object']).columns

# Data Normalization for Numerical Columns
scaler = MinMaxScaler()
data[numeric_columns] = scaler.fit_transform(data[numeric_columns])

# Label Encoding for Categorical Columns
label_encoder = LabelEncoder()
data[categorical_columns] = data[categorical_columns].apply(lambda col: label_encoder.fit_transform(col))

#Data Standardization for Numerical Columns 
scaler_standard = StandardScaler()
data[numeric_columns] = scaler_standard.fit_transform(data[numeric_columns])



In [13]:
#Feature selection - first drop columns that are not needed
df = data.drop(['X', 'Y', 'OBJECTID', 'EVENT_UNIQUE_ID', 'HOOD_158' ,'HOOD_140', 'NEIGHBOURHOOD_140' ,'LONG_WGS84',
        'LAT_WGS84', 'PRIMARY_OFFENCE', 'OCC_DATE', 'OCC_YEAR', 'OCC_MONTH', 'OCC_DOW', 'OCC_DAY', 'OCC_HOUR',
               'REPORT_DATE', 'REPORT_YEAR', 'REPORT_MONTH', 'REPORT_DOW', 'REPORT_DAY', 'REPORT_DOY', 'REPORT_HOUR',
               'DIVISION', 'LOCATION_TYPE', 'PREMISES_TYPE', 'BIKE_MAKE', 'BIKE_MODEL', 'BIKE_TYPE', 'BIKE_COLOUR',
               'STATUS', 'NEIGHBOURHOOD_158', 'BIKE_MODEL_CAT', 'NEIGHBOURHOOD_158_CAT', 'OCC_DOY', 'BIKE_COLOUR_CAT',
               'BIKE_MAKE_CAT'], axis=1)

In [14]:
#feature selection
X = df.drop('STATUS_IND', axis=1)
y = df['STATUS_IND']



In [15]:
from sklearn.model_selection import train_test_split

#Train, test data splitting
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
